USERS = "users"
HOMES = "homes"
ROOMS = "rooms"
DESIGN_CONVERSATIONS = "design_conversations"
DESIGN_REQUIREMENTS = "design_requirements"
DESIGN_VERSIONS = "design_versions"
INSPIRATIONS = "inspirations"
DESIGN_SCORES = "design_scores"
CONTRACTOR_BRIEFS = "contractor_briefs"
PROFESSIONALS = "professionals"
SHARED_BRIEFS = "shared_briefs"
# Non-sensitive preference memory and generation audit trail (opt-in training later).
DESIGN_MEMORY = "design_memory"
GENERATION_EVENTS = "generation_events"
REGION_CONSTRAINTS = "region_constraints"
